name: Deploy via SSH

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ssh-deploy
  cancel-in-progress: true

jobs:
  build:
    name: Install and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dist
          path: ./build
          retention-days: 1

  deploy-ssh:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy via SSH
    environment: production

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: dist
          path: ./dist

      - name: Deploy to Staging Server
        uses: easingthemes/ssh-deploy@main  # 使用最新稳定版本
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH 私钥
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}          # 服务器 IP 或域名
          REMOTE_USER: ${{ secrets.REMOTE_USER }}          # SSH 登录用户名
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}          # SSH 端口（默认 22）
          SOURCE: ./dist                                    # 本地构建目录
          TARGET: /var/www/                               # 服务器目标路径（需存在）
          EXCLUDE: "/dist/, /node_modules/"                # 排除目录（可选）
          SCRIPT_BEFORE: |
            echo "Before Deployment:"
            whoami
            ls -al /var/www/
          SCRIPT_AFTER: |
            echo "After Deployment:"
            whoami
            ls -al /var/www/
            echo "RSYNC Output: $RSYNC_STDOUT"
